### ISSUE TITLE
Issue running test.py

### ISSUE THREAD

**Issue by nahidalam** [ewrfcas/Face-Super-Resolution#25]
Python version `3.6`
Pytorch version `1.4`

I downloaded the pre-trained models and running `test.py` 

```
python test.py
```

But getting the below error

```
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    output_img, rec_img = sr_forward(img)
  File "test.py", line 73, in sr_forward
    img_aligned, M = dlib_detect_face(img, padding=padding, image_size=(128, 128), moving=moving)
  File "/home/ec2-user/mydir/Face-Super-Resolution/dlib_alignment.py", line 68, in dlib_detect_face
    dets = dlib_detector(img, 0)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.fhog_object_detector, image: array, upsample_num_times: int=0) -> _dlib_pybind11.rectangles

Invoked with: <_dlib_pybind11.fhog_object_detector object at 0x7fd51a70d5e0>, None, 0

```

Please suggest.

**Comment by mjforan** [comment]
You have to change the input image path in test.py
